repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: gitlint
        name: gitlint
        entry: poetry run gitlint
        args: [--staged, --msg-filename]
        language: system
        stages: [commit-msg]
-   repo: local
    hooks:
    -   id: markdownlint
        name: markdownlint
        entry: markdownlint
        language: system
        types: [markdown]
-   repo: local
    hooks:
    -   id: mdformat
        name: mdformat
        entry: poetry run mdformat --wrap 80 README.md docs/
        language: system
        types: [markdown]
