repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v8.0.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
    -   id: markdownlint
        name: Markdownlint
        description: Run markdownlint on your Markdown files
        entry: mdl -c .pre-commit-config.yaml
        language: ruby
        types: [markdown]
-   repo: local
    hooks:
    -   id: mdformat
        name: mdformat
        entry: poetry run mdformat --wrap 80
        language: system
        types: [markdown]
