[build]
    command = """
        pip install -q poetry && \
        poetry export -f requirements.txt --without-hashes -o requirements.txt && \
        pip install -r requirements.txt && \
        mkdocs build
    """
    ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./docs"
    publish = "site"
