on:
  push:
    paths:
      - .github/**
      - docs/**
      - README.md
  pull_request:
    paths:
      - .github/**
      - docs/**
      - README.md
  workflow_dispatch:

name: CI

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: jmgilman
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run mdlint
        run: nix develop -c mdl docs/
      - name: Run mdformat
        run: nix develop -c mdformat --check docs/
  build:
    name: Test build
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: jmgilman
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run mkdocs
        run: nix develop -c mkdocs build --strict --verbose
